spring:
  profiles:
    active: local
  application:
    name: ecommerce

  datasource:
    url: jdbc:mysql://localhost:3306/database_name?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: login
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: "username"
    password: "password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: yourtoken
      expiration: 86400000
      refresh-token:
        expiration: 604800000

resilience4j.ratelimiter:
  instances:
    apiLimiter:
      limitForPeriod: 5
      limitRefreshPeriod: 60s
      timeoutDuration: 0s